# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Introduction
    url: /#papers
    weight: 11
  - name: Organization
    url: /#talks
    weight: 12
  - name: Major
    url: /#news
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    identifier: projects
    url: projects/
    weight: 30
  - name: MyBucket
    url: projects/scikit
    parent: projects
    weight: 30.1
  - name: QatarDraw
    url: projects/pandas
    parent: projects
    weight: 30.2
  - name: Galendar
    url: projects/pytorch
    parent: projects
    weight: 30.3
